apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
  labels: 
    name: cm
    component: backend
    project: expense
data:
  DB-HOST: mysql
  #mysql compose service name given while building the docker image
------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    component: backend
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: backend
      tier: app
  template:
    metadata:
      project: expense
      component: backend
      tier: app
    spec:
      containers:
      - name: backend
        image: learndevops143/backend:v1.0
        envFrom:
        - configMapRef:
            name: backend
------
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    component: backend
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
